### ISSUE TITLE
Issues Pulling Spring 2025 Data

### ISSUE THREAD

**Issue by ajaygandecha** [SabaEskandarian/COMP_classes#2]
Hello @SabaEskandarian! I have been experimenting a few times over the last few days trying to create a pull request to retrieve Spring 2025 data into the existing course exploration tool. I tried following the steps listed in `gather_data.py` and successfully copied a `curl` command into `COMP_search_curl.sh`. However, upon running either `gather_data.py` or `repeat.sh`, no classes are scraped and the following is output to `dept_response.txt`:

```txt
<html><head><title>302 Moved Temporarily</title></head>
<body bgcolor="#FFFFFF">
<p>This document you requested has moved 
temporarily.</p>
<p>It's now at <a href="https://cs.cc.unc.edu/psc/campus/EMPLOYEE/SA/c/SA_LEARNER_SERVICES.CLASS_SEARCH.GBL?cmd=login&amp;errorCode=129&amp;languageCd=ENG&amp;">https://cs.cc.unc.edu/psc/campus/EMPLOYEE/SA/c/SA_LEARNER_SERVICES.CLASS_SEARCH.GBL?cmd=login&amp;errorCode=129&amp;languageCd=ENG&amp;</a>.</p>
</body></html>
```

I tried changing the `curl` command to use the new URL, and this also fails. I tried running the generated department `curl` commands in the terminal, and there is no discernible output.

The only `curl` command which worked successfully to pull COMP data was after I manually selected "COMP" in search and changed the filter parameters to limit to courses with a number <= 915. Copying this POST request's `curl` command and running it in the terminal seems to result in retrieving the correct HTML.

I tried to run a diff comparison on the curl command that worked vs the one that the Python script generated. There are no differences except for the `--data-raw` section. I hit a dead end at this point and was curious if you had any ideas as to what may be broken here!

**Comment by SabaEskandarian** [comment]
Not sure what went wrong for you. I just added spring 2025 data, and it's working fine. 
https://crypto.unc.edu/UNC_classes/spring2025/
